// ── ACCOUNT PROFILE & SETTINGS BOARD: Profile.jsx ──
// - Purpose: Shows account credentials, billing plan metadata, and logout button.
// - Features: Circular avatar letter-generator, user session indicators, and plan details checklist.
// - Editing Tip: To change the billing plan details displayed on the page, look under the second `<article>` box below.

import { useNavigate } from 'react-router-dom'
import { clearSession } from './api/client'

export default function ProfilePage() {
  const navigate = useNavigate()

  // SESSION PROFILE: Gathers credentials from browser's local cache.
  const user = JSON.parse(localStorage.getItem('user') || '{}')

  // SESSION DESTRUCTION: Logs user out and routes them to homepage.
  const logout = () => {
    clearSession()
    navigate('/')
  }

  return (
    /* 
      PAGE BASE LAYER: Workspace layout wrapper.
      - Styled by .workspace-page (index.css).
    */
    <div className="workspace-page mobile-page mobile-profile-page">
      
      {/* HEADER HERO BAR: Account page title and logout button */}
      <header className="workspace-hero mobile-page-hero">
        <div>
          <span className="eyebrow">Account</span>
          <h1>Workspace Profile</h1>
          <p>Manage session access, plan details, and creator workspace identity.</p>
        </div>
        
        {/* LOGOUT BUTTON: Red-accented button (.btn-danger in index.css). */}
        <button className="btn btn-danger" type="button" onClick={logout}>
          <span className="material-symbols-outlined">logout</span>
          Logout
        </button>
      </header>

      {/* 
        PROFILE GRID: Displays account panels in columns on desktop.
        - Styled by .profile-grid and .premium-profile-grid in index.css.
      */}
      <section className="profile-grid premium-profile-grid mobile-card-stack">
        
        {/* 
          PANEL 1: User Identity Details.
          - Avatar: A circle generated by pulling the first letter of user's name (or email) and capitalising it (.profile-avatar in index.css).
          - Details: Display name and email loaded from browser cache.
        */}
        <article className="profile-panel">
          {/* Circular letter avatar (picks first letter, defaults to 'R' for Reclipper) */}
          <div className="profile-avatar">{(user.name || user.email || 'R').slice(0, 1).toUpperCase()}</div>
          <div>
            <h2>{user.name || 'Reclipper User'}</h2>
            <p>{user.email || 'No email saved yet'}</p>
          </div>
        </article>

        {/*
          PANEL 2: Workspace access summary.
          - Shows the account's real plan when the server provides one; otherwise
            describes what this workspace includes (no fake "Pro" placeholder).
        */}
        <article className="profile-panel">
          <span className="eyebrow">{user.plan ? 'Current plan' : 'Workspace access'}</span>
          <h2>{user.plan || 'Creator workspace'}</h2>
          <p>AI overlays, Instagram captions, editor, projects, mobile preview, and export review.</p>
        </article>

      </section>
    </div>
  )
}
